inputs:
  ref_prompt: "A `cat on the right and a `dog on the left."
  base_prompt: "A `cat on the right and a `dog on the left."
  negative_prompt: ""
  custom_prompts: 
    - "A <cat2_1> `<cat2_2> on the right and a <cat2_1> `<cat2_2> on the left."
    - "A <dog6_1> `<dog6_2> on the right and a <dog6_1> `<dog6_2> on the left."
  # ref_image_path: "examples/mask_cat.png"
  # ref_mask_paths:
  #   - "examples/dog-cat-dog_rect_0.png"
  #   - "examples/dog-cat-dog_rect_1.png" 
  #   - "examples/dog-cat-dog_rect_2.png" 
  init_mask_from_points: False
  init_image_path: ~
  init_mask_path: ~       
  edlora_paths:
    - "experiments/chilloutmix/cat2/models/edlora_model-latest.pth"
    - "experiments/chilloutmix/dog6/models/edlora_model-latest.pth"
  load_edlora: True
  lora_alpha: 0.7

outputs:
  # outroot: "outputs/dog_pet_cat1_dog6_rect"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"


base_model:
  sd_ckpt: "experiments/pretrained_models/chilloutmix" #stable-diffusion-v1-5" #
  variant: ""

sd_t2i:
  # height: 768 #512
  # width: 768 #512
  guidance_scale: 7.5
  num_inference_steps: 100
  start_seed: 0
  batch_size: 8
  n_batches: 1
  verbose: False

attention_operations:
  attn_guidance_end: 60 # 變長
  attn_guidance_interval: 1
  attn_guidance_weight: 7.0
  custom_attn_guidance_factor: [1.2, 1.2, 1.2] #[1.0, 1.0] #1.2

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["key"] #[query", "key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]      
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]    

  mask_refinement_start: 50
  mask_refinement_end: 80 # 變短
  mask_update_interval: 5
  mask_overlap_threshold: 0 #0.7
  mask_refinement_penalty: False # True #
  num_kmeans_init: 100 # 改
  num_clusters: 6
  rect_mask: False #True # 長方形

  use_loss_mask: True
  visualization: True

