inputs:
  ref_prompt: "A rectangle layout."
  base_prompt: "A `flower in a `vase."
  negative_prompt: ""
  custom_prompts:
    - "A <flower_1_1> `<flower_1_2> in a vase."
    - "flower in a `<vase_1> `<vase_2>."
  ref_image_path: "examples/1_vase/layout_mask.png"
  ref_mask_paths:
    - "examples/1_vase/flower_mask.png"
    - "examples/1_vase/vase_mask.png"
  init_mask_from_points: False
  mask_center_points:
    - [350, 200]
    - [150, 300]
  init_image_path: ~
  init_mask_path: ~
  edlora_paths:
    - "experiments/flower_1/models/edlora_model-latest.pth"
    - "experiments/vase/models/edlora_model-latest.pth"
  load_edlora: True
  lora_alpha: 0.75

outputs:
  outroot: "outputs/2_5"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"


base_model:
  sd_ckpt: "experiments/pretrained_models/chilloutmix"
  variant: ""

sd_t2i:
  height: 512
  width: 512
  guidance_scale: 7.5
  num_inference_steps: 200
  start_seed: 1234567
  batch_size: 16
  n_batches: 1
  verbose: False

attention_operations:
  attn_guidance_end: 60
  attn_guidance_interval: 1
  attn_guidance_weight: 7
  custom_attn_guidance_factor: 1.5

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]

  mask_refinement_start: 50
  mask_refinement_end: 80
  mask_update_interval: 5
  mask_overlap_threshold: 0.5
  num_kmeans_init: 200
  rect_mask: True

  use_loss_mask: True
  visualization: False



