inputs:
  ref_prompt: "A rectangle layout."
  base_prompt: "A `cat wearing `wearable glasses in a watercolor style."
  negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
  custom_prompts:
    - "A <gray_cat_1> `<gray_cat_2> wearing wearable glasses in a watercolor style"
    # - "A <cat2_1> `<cat2_2> wearing <cat2_1> `<cat2_2> in a watercolor style."
    - "A cat wearing <wearable_glasses_1> `<wearable_glasses_2> in a watercolor style."
    - "A cat wearing wearable glasses in a <watercolor_1> `<watercolor_2> style."
  ref_image_path: "examples/style/ref_image_1.png"
  ref_mask_paths:
    - "examples/style/ref_image_1_cat.png"
    - "examples/style/ref_image_1_glasses.png"
    - "examples/all_white.png"
  init_mask_from_points: False
  mask_center_points:
    # - [350, 200]
    # - [150, 300]
  init_image_path: ~
  init_mask_path: ~
  edlora_paths:
    # - "experiments/cat2/models/edlora_model-latest.pth"
    - "experiments/ED-LoRAs/real/gray_cat.pth"
    - "experiments/wearable_glasses/models/edlora_model-latest.pth"
    - "experiments/watercolor/models/edlora_model-latest.pth"
  load_edlora: True
  lora_alpha: 0.5

outputs:
  outroot: "outputs/4_map"
  image_outdir: "inference_results"
  latents_outdir: "inverted_latents"
  self_attn_outdir: "self_attn"
  cross_attn_outdir: "cross_attn"
  feature_mask_outdir: "feature_mask"
#

base_model:
  sd_ckpt: "experiments/pretrained_models/chilloutmix"
  variant: ""

sd_t2i:
  height: 512
  width: 512
  guidance_scale: 7.5
  num_inference_steps: 200
  start_seed: 37
  batch_size: 6
  n_batches: 1
  verbose: False

attention_operations:
  attn_guidance_end: 60
  attn_guidance_interval: 1
  attn_guidance_weight: 3.0
  custom_attn_guidance_factor: 1.5

  processor_filter_guidance: '.*up_blocks\.1\.attentions\.0.*attn1.*'
  params_guidance: ["query", "key"]
  processor_filter_mask: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_mask: ['attention_probs']
  processor_filter_merge: '.*up_blocks.*'
  params_merge: ["feature_output"]
  processor_filter_view_sa: '.*up_blocks\.2\.attentions\.2.*attn1.*'
  params_view_sa: ["attention_probs"]
  processor_filter_view_ca: '.*up_blocks\.2\.attentions\.1.*attn2.*'
  params_view_ca: ["attention_probs"]

  mask_refinement_start: 50
  mask_refinement_end: 80
  mask_update_interval: 5
  mask_overlap_threshold: 0.99
  num_kmeans_init: 200
  rect_mask: True

  use_loss_mask: True
  visualization: False



